version: '3'

services:
  app:
    container_name: enigma_explorer_api
    hostname: enigma_explorer_api
    restart: always
    build: .
    ports:
      - '${ENIGMA_API_PORT}:${ENIGMA_API_PORT}'
    network_mode: host

  mongo:
    container_name: engima_explorer_db
    hostname: engima_explorer_db
    image: mongo:4.0
    volumes:
      - './data:/data/db'
    ports:
      - '27017:27017'
